### ISSUE TITLE
Publish version 0.2 to PyPI

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-allattachments#1]
I've made the plugin compatible with Trac 1.0+. Could you please either publish a new version to [PyPI](https://pypi.python.org/pypi/AllAttachmentsMacro) or grant me package owner rights and I'll update?

**Comment by mitar** [comment]
What is your PyPi username?

**Comment by mitar** [comment]
Also, I just published 0.2.

**Comment by mitar** [comment]
Added `rjollos` as well on PyPi.

**Comment by rjollos** [comment]
Yes rjollos is correct username. Thanks!
